export const SECTEURS_EVACUES = [
  "Saumos",
  "Le Porge",
  "Le Temple",
  "Lège-Cap-Ferret (bourg)",
  "Claouey",
  "Le Four",
  "Les Jacquets",
  "Petit Piquey",
  "Grand Piquey",
  "Arès",
  "Andernos-les-Bains",
  "Lacanau (secteur Andrauts)",
  "Lacanau (secteur Mistre)",
  "Saint-Aubin-de-Médoc",
  "Saint-Médard-en-Jalles",
  "Martignas-sur-Jalle",
  "Saint-Jean-d'Illac",
  "Mérignac",
  "Eysines",
  "Le Haillan",
  "Marcheprime",
  "Le Barp",
  "Biganos",
  "Mios",
  "Cestas",
  "Autre",
];
